# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu: 
  - name: 项目
    submenu:
      - name: MicroBam
        link: /projects/microbam
      - name: OurLegacy
        link: /projects/ourlegacy
  - name: 博文
    link: /
  - name: 标签
    link: /tags
  - name: 关于
    link: /about
  - name: 关注我
    submenu:
      - name: GitHub
        icon: github
        link: http://github.com/AlbertRobot
      - name: LinkedIn
        icon: linkedin-square
        link: https://www.linkedin.com/in/xianghui-zhao-89ab3367/
      - name: Zhihu
        icon: twitter
        link: https://www.zhihu.com/people/zhaoxh1989
    
